<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Onlinefragebogen Formular Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'info@lichtblickpflege.de',
		'to' => 'info@lichtblickpflege.de'
	),
	'fields' => array(
		'custom_U14646' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Adresse der Pflegebedürftigen',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Adresse der Pflegebedürftigen\' is required.'
			)
		),
		'custom_U14718' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Beginn der Pflege',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Beginn der Pflege\' is required.'
			)
		),
		'custom_U14539' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Name des Pflegebedürftigen',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name des Pflegebedürftigen\' is required.'
			)
		),
		'custom_U14526' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Gewicht',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Gewicht\' is required.'
			)
		),
		'custom_U14906' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Größe',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Größe\' is required.'
			)
		),
		'custom_U14543' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Alter',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Alter\' is required.'
			)
		),
		'custom_U15058' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Geburtsdatum',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Geburtsdatum\' is required.'
			)
		),
		'custom_U14629' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Pflegegrad',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Pflegegrad\' is required.'
			)
		),
		'custom_U14678' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Mobilität',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U14919' => array(
			'order' => 58,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'custom_U14857' => array(
			'order' => 59,
			'type' => 'string',
			'label' => 'Straße, Hausnummer',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Straße, Hausnummer\' is required.'
			)
		),
		'custom_U14722' => array(
			'order' => 60,
			'type' => 'string',
			'label' => 'PLZ, Ort',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'PLZ, Ort\' is required.'
			)
		),
		'custom_U14977' => array(
			'order' => 61,
			'type' => 'string',
			'label' => 'EMail',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'EMail\' is required.'
			)
		),
		'custom_U15054' => array(
			'order' => 62,
			'type' => 'string',
			'label' => 'Telefonnummer',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Telefonnummer\' is required.'
			)
		),
		'custom_U14795' => array(
			'order' => 73,
			'type' => 'string',
			'label' => 'Wie haben sie von uns erfahren',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U14990' => array(
			'order' => 72,
			'type' => 'radiogroup',
			'label' => 'Internet vorhanden',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Internet vorhanden\' has an invalid value.'
			)
		),
		'custom_U14999' => array(
			'order' => 40,
			'type' => 'radiogroup',
			'label' => 'Hund',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Hund\' has an invalid value.'
			)
		),
		'custom_U14593' => array(
			'order' => 55,
			'type' => 'radiogroup',
			'label' => 'Versorgung der Haustiere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Versorgung der Haustiere\' has an invalid value.'
			)
		),
		'custom_U15026' => array(
			'order' => 10,
			'type' => 'radiogroup',
			'label' => 'Pflegedienst ist beauftragt',
			'required' => true,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'required' => 'Field \'Pflegedienst ist beauftragt\' is required.',
				'format' => 'Field \'Pflegedienst ist beauftragt\' has an invalid value.'
			)
		),
		'custom_U15008' => array(
			'order' => 32,
			'type' => 'radiogroup',
			'label' => 'Körperpflege',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Körperpflege\' has an invalid value.'
			)
		),
		'custom_U14910' => array(
			'order' => 46,
			'type' => 'radiogroup',
			'label' => 'Blumen gießen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Blumen gießen\' has an invalid value.'
			)
		),
		'custom_U14941' => array(
			'order' => 4,
			'type' => 'radiogroup',
			'label' => 'Geschlecht',
			'required' => true,
			'optionItems' => array(
				'männlich',
				'weiblich'
			),
			'errors' => array(
				'required' => 'Field \'Geschlecht\' is required.',
				'format' => 'Field \'Geschlecht\' has an invalid value.'
			)
		),
		'custom_U15062' => array(
			'order' => 24,
			'type' => 'radiogroup',
			'label' => 'Schlaganfall',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Schlaganfall\' has an invalid value.'
			)
		),
		'custom_U15045' => array(
			'order' => 16,
			'type' => 'radiogroup',
			'label' => 'Geistig behindert',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Geistig behindert\' has an invalid value.'
			)
		),
		'custom_U15089' => array(
			'order' => 30,
			'type' => 'radiogroup',
			'label' => 'Duschen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Duschen\' has an invalid value.'
			)
		),
		'custom_U14959' => array(
			'order' => 71,
			'type' => 'radiogroup',
			'label' => 'eigener Fernseher',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'eigener Fernseher\' has an invalid value.'
			)
		),
		'custom_U14968' => array(
			'order' => 33,
			'type' => 'radiogroup',
			'label' => 'Mobilisierung',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Mobilisierung\' has an invalid value.'
			)
		),
		'custom_U14557' => array(
			'order' => 27,
			'type' => 'radiogroup',
			'label' => 'Arztbesuche',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Arztbesuche\' has an invalid value.'
			)
		),
		'custom_U14981' => array(
			'order' => 51,
			'type' => 'radiogroup',
			'label' => 'leichte Gartenarbeit',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'leichte Gartenarbeit\' has an invalid value.'
			)
		),
		'custom_U14735' => array(
			'order' => 37,
			'type' => 'radiogroup',
			'label' => 'Weitere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Weitere\' has an invalid value.'
			)
		),
		'custom_U14575' => array(
			'order' => 45,
			'type' => 'radiogroup',
			'label' => 'Aufräumen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Aufräumen\' has an invalid value.'
			)
		),
		'custom_U14726' => array(
			'order' => 44,
			'type' => 'radiogroup',
			'label' => 'Geschäfte des täglichen Lebens fußläufig erreichbar',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Geschäfte des täglichen Lebens fußläufig erreichbar\' has an invalid value.'
			)
		),
		'custom_U15035' => array(
			'order' => 41,
			'type' => 'radiogroup',
			'label' => 'Katze',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Katze\' has an invalid value.'
			)
		),
		'custom_U14548' => array(
			'order' => 49,
			'type' => 'radiogroup',
			'label' => 'Fenster putzen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Fenster putzen\' has an invalid value.'
			)
		),
		'custom_U14530' => array(
			'order' => 67,
			'type' => 'radiogroup',
			'label' => 'Führerschein notwendig',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Führerschein notwendig\' has an invalid value.'
			)
		),
		'custom_U14829' => array(
			'order' => 63,
			'type' => 'radiogroup',
			'label' => 'Geschlecht der Pflegekraft',
			'required' => false,
			'optionItems' => array(
				'männlich',
				'weiblich'
			),
			'errors' => array(
				'format' => 'Field \'Geschlecht der Pflegekraft\' has an invalid value.'
			)
		),
		'custom_U14799' => array(
			'order' => 65,
			'type' => 'radiogroup',
			'label' => 'Gewünschtes Alter der Pflegekraft',
			'required' => false,
			'optionItems' => array(
				'30-40',
				'40-50',
				'50-60'
			),
			'errors' => array(
				'format' => 'Field \'Gewünschtes Alter der Pflegekraft\' has an invalid value.'
			)
		),
		'custom_U14691' => array(
			'order' => 38,
			'type' => 'radiogroup',
			'label' => 'Sind nächtliche Einsätze notwendig',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Sind nächtliche Einsätze notwendig\' has an invalid value.'
			)
		),
		'custom_U14848' => array(
			'order' => 69,
			'type' => 'radiogroup',
			'label' => 'Unterbringung',
			'required' => false,
			'optionItems' => array(
				'eigener Bereich',
				'Zimmer'
			),
			'errors' => array(
				'format' => 'Field \'Unterbringung\' has an invalid value.'
			)
		),
		'custom_U14932' => array(
			'order' => 50,
			'type' => 'radiogroup',
			'label' => 'Kochen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Kochen\' has an invalid value.'
			)
		),
		'custom_U14950' => array(
			'order' => 68,
			'type' => 'radiogroup',
			'label' => 'Raucher',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Raucher\' has an invalid value.'
			)
		),
		'custom_U14611' => array(
			'order' => 28,
			'type' => 'radiogroup',
			'label' => 'Ausflüge',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Ausflüge\' has an invalid value.'
			)
		),
		'custom_U14861' => array(
			'order' => 42,
			'type' => 'radiogroup',
			'label' => 'Andere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Andere\' has an invalid value.'
			)
		),
		'custom_U14660' => array(
			'order' => 53,
			'type' => 'radiogroup',
			'label' => 'Speisenplanung',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Speisenplanung\' has an invalid value.'
			)
		),
		'custom_U14838' => array(
			'order' => 66,
			'type' => 'radiogroup',
			'label' => 'Betreuungserfahrung',
			'required' => false,
			'optionItems' => array(
				'erforderlich',
				'nicht erforderlich'
			),
			'errors' => array(
				'format' => 'Field \'Betreuungserfahrung\' has an invalid value.'
			)
		),
		'custom_U14762' => array(
			'order' => 18,
			'type' => 'radiogroup',
			'label' => 'Inkontinenz',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Inkontinenz\' has an invalid value.'
			)
		),
		'custom_U14633' => array(
			'order' => 26,
			'type' => 'radiogroup',
			'label' => 'An- und Auskleiden',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'An- und Auskleiden\' has an invalid value.'
			)
		),
		'custom_U14620' => array(
			'order' => 43,
			'type' => 'radiogroup',
			'label' => 'Wohnverhältnisse',
			'required' => false,
			'optionItems' => array(
				'städtisch',
				'ländlich'
			),
			'errors' => array(
				'format' => 'Field \'Wohnverhältnisse\' has an invalid value.'
			)
		),
		'custom_U14700' => array(
			'order' => 29,
			'type' => 'radiogroup',
			'label' => 'Behördengänge',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Behördengänge\' has an invalid value.'
			)
		),
		'custom_U14879' => array(
			'order' => 14,
			'type' => 'radiogroup',
			'label' => 'Demenz',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Demenz\' has an invalid value.'
			)
		),
		'custom_U14786' => array(
			'order' => 22,
			'type' => 'radiogroup',
			'label' => 'Parkinson',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Parkinson\' has an invalid value.'
			)
		),
		'custom_U14888' => array(
			'order' => 20,
			'type' => 'radiogroup',
			'label' => 'MS-Patient',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'MS-Patient\' has an invalid value.'
			)
		),
		'custom_U15107' => array(
			'order' => 70,
			'type' => 'radiogroup',
			'label' => 'Eigenes Bad',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Eigenes Bad\' has an invalid value.'
			)
		),
		'custom_U14517' => array(
			'order' => 23,
			'type' => 'radiogroup',
			'label' => 'Rheuma',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Rheuma\' has an invalid value.'
			)
		),
		'custom_U14870' => array(
			'order' => 56,
			'type' => 'radiogroup',
			'label' => 'Weitere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Weitere\' has an invalid value.'
			)
		),
		'custom_U14923' => array(
			'order' => 25,
			'type' => 'radiogroup',
			'label' => 'Andere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Andere\' has an invalid value.'
			)
		),
		'custom_U14650' => array(
			'order' => 34,
			'type' => 'radiogroup',
			'label' => 'Nahrungsaufnahme',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Nahrungsaufnahme\' has an invalid value.'
			)
		),
		'custom_U15080' => array(
			'order' => 47,
			'type' => 'radiogroup',
			'label' => 'Bügeln',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Bügeln\' has an invalid value.'
			)
		),
		'custom_U15071' => array(
			'order' => 12,
			'type' => 'radiogroup',
			'label' => 'Alzheimer',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Alzheimer\' has an invalid value.'
			)
		),
		'custom_U14566' => array(
			'order' => 54,
			'type' => 'radiogroup',
			'label' => 'Wäsche waschen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Wäsche waschen\' has an invalid value.'
			)
		),
		'custom_U14753' => array(
			'order' => 31,
			'type' => 'radiogroup',
			'label' => 'Freizeitgestaltung',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Freizeitgestaltung\' has an invalid value.'
			)
		),
		'custom_U14897' => array(
			'order' => 19,
			'type' => 'radiogroup',
			'label' => 'Krebs',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Krebs\' has an invalid value.'
			)
		),
		'custom_U14709' => array(
			'order' => 17,
			'type' => 'radiogroup',
			'label' => 'Herz-Kreislauf',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Herz-Kreislauf\' has an invalid value.'
			)
		),
		'custom_U14820' => array(
			'order' => 52,
			'type' => 'radiogroup',
			'label' => 'Sauber machen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Sauber machen\' has an invalid value.'
			)
		),
		'custom_U14584' => array(
			'order' => 36,
			'type' => 'radiogroup',
			'label' => 'Stehen, Gehen oder Betten',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Stehen, Gehen oder Betten\' has an invalid value.'
			)
		),
		'custom_U14744' => array(
			'order' => 57,
			'type' => 'radiogroup',
			'label' => 'Anrede',
			'required' => true,
			'optionItems' => array(
				'Herr',
				'Frau'
			),
			'errors' => array(
				'required' => 'Field \'Anrede\' is required.',
				'format' => 'Field \'Anrede\' has an invalid value.'
			)
		),
		'custom_U14669' => array(
			'order' => 48,
			'type' => 'radiogroup',
			'label' => 'Einkaufen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Einkaufen\' has an invalid value.'
			)
		),
		'custom_U14682' => array(
			'order' => 35,
			'type' => 'radiogroup',
			'label' => 'Toilettengang',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Toilettengang\' has an invalid value.'
			)
		),
		'custom_U14771' => array(
			'order' => 64,
			'type' => 'radiogroup',
			'label' => 'Gewünschte Deutschkenntnisse',
			'required' => false,
			'optionItems' => array(
				'Grundkenntnisse',
				'mittlere Kenntnisse',
				'gute Kenntnisse',
				'sehr gute Kenntnisse'
			),
			'errors' => array(
				'format' => 'Field \'Gewünschte Deutschkenntnisse\' has an invalid value.'
			)
		),
		'custom_U15017' => array(
			'order' => 39,
			'type' => 'radiogroup',
			'label' => 'Weitere Personen im Haushalt',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Weitere Personen im Haushalt\' has an invalid value.'
			)
		),
		'custom_U14811' => array(
			'order' => 15,
			'type' => 'radiogroup',
			'label' => 'Dialysepatient',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Dialysepatient\' has an invalid value.'
			)
		),
		'custom_U14602' => array(
			'order' => 13,
			'type' => 'radiogroup',
			'label' => 'Arthrose',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Arthrose\' has an invalid value.'
			)
		),
		'custom_U15098' => array(
			'order' => 21,
			'type' => 'radiogroup',
			'label' => 'Osteoporose',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Field \'Osteoporose\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
